# Basics of NLP

In [2]:
# INSTALLING LIBRARIES
##!pip install nltk

Tokenization :
    Tokenization is a process of breaking down a given paragraph of text into a list of sentence or words. when paragraph is broken down into list of sentences, it is called sentence tokenization

# Word Tokenization

In [3]:
#IMPORTING REQUIRED FILE
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
#Define your text or import from other source
text='Iam learning natural language processing'
#tokenizing
print(word_tokenize(text))

['Iam', 'learning', 'natural', 'language', 'processing']


[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


# Sentence Tokenization

In [4]:
from nltk.tokenize import sent_tokenize
text="our company growth is 25%. Good job Mr.Balaji"
print(sent_tokenize(text))

['our company growth is 25%.', 'Good job Mr.Balaji']


# Regular Expressions

In [5]:
from nltk.tokenize import regexp_tokenize 
#Sample text
text="NLP is fun and can deal with texts and sounds, but can't deal with images. we have session at 11 AM! we can earn lot of $"
#Print word by word that contains all small case and starts from all small case and starts from small a to z. 
regexp_tokenize(text,"[a-z]+")

['is',
 'fun',
 'and',
 'can',
 'deal',
 'with',
 'texts',
 'and',
 'sounds',
 'but',
 'can',
 't',
 'deal',
 'with',
 'images',
 'we',
 'have',
 'session',
 'at',
 'we',
 'can',
 'earn',
 'lot',
 'of']

In [6]:
#extra quote gets you word like can't,don't
regexp_tokenize(text,"[a-z']+")

['is',
 'fun',
 'and',
 'can',
 'deal',
 'with',
 'texts',
 'and',
 'sounds',
 'but',
 "can't",
 'deal',
 'with',
 'images',
 'we',
 'have',
 'session',
 'at',
 'we',
 'can',
 'earn',
 'lot',
 'of']

In [7]:
## Print word by word that contains all caps from A to Z
regexp_tokenize(text,"[A-Z]+")

['NLP', 'AM']

In [10]:
#to get everything in one line
regexp_tokenize(text,"[\a-z]+")

["NLP is fun and can deal with texts and sounds, but can't deal with images. we have session at 11 AM! we can earn lot of $"]

In [11]:
#Anything start with caret symbol ^ is taken as not equal to

regexp_tokenize(text,"[^a-z]+")

['NLP ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ', ',
 ' ',
 "'",
 ' ',
 ' ',
 ' ',
 '. ',
 ' ',
 ' ',
 ' ',
 ' 11 AM! ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' $']

In [12]:
#only numbers
regexp_tokenize(text,"[0-9]+")

['11']

In [13]:
#without number
regexp_tokenize(text,"[^0-9]+")

["NLP is fun and can deal with texts and sounds, but can't deal with images. we have session at ",
 ' AM! we can earn lot of $']

In [15]:
#Dollar symbol from text
regexp_tokenize(text,"[$]")

['$']

# STOP WORDS

stopwords are commonly occuring words which doesn't have any meaning or impact for processing. It is removed in pre processing (a,an,the,at etc,.)

In [25]:
#this is how we import stop words
import nltk
from nltk.corpus import stopwords

In [26]:
#if you are getting error on this you can also do nltk.download("stopwords")

In [27]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jijin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [28]:
#there will be 179 words default present in stopwords
stopwords=stopwords.words('english')

In [29]:
print(stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [30]:
len(stopwords)

179

In [31]:
# we can also do it simply reducing steps
stopset=set(nltk.corpus.stopwords.words('english'))


In [32]:
stopset

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [33]:
len(stopset)

179

In [34]:
#Adding custom stopwords
stopset.update(('new','old'))

In [35]:
len(stopset)

181

In [37]:
#Similar to stop words we can also ignore punctuations in our sentence

# import string for getting punctuations

import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [38]:
# Excercise : Remove stopwords and punctuations from the text 

text = "India (Hindi : Bharat),officially the republic of india, is a country in south asia. It is the seventh largest country by size and population ;"

# creating an empty list top load the cleaned data
cleaned_text=[]

punct=string.punctuation
stopwords=set(nltk.corpus.stopwords.words('english'))

for word in nltk.word_tokenize(text):
    if word not in punct:
        if word not in stopwords:
            cleaned_text.append(word)
            
print('Original length ==> ',len(text))
print('Length of cleaned text ==>',len(cleaned_text))
print('\n',cleaned_text)

Original length ==>  143
Length of cleaned text ==> 15

 ['India', 'Hindi', 'Bharat', 'officially', 'republic', 'india', 'country', 'south', 'asia', 'It', 'seventh', 'largest', 'country', 'size', 'population']


In [39]:
#It is taken as it contains caps I 
#convert into lowercase
print(text.lower())

india (hindi : bharat),officially the republic of india, is a country in south asia. it is the seventh largest country by size and population ;


In [40]:
text= text.lower()

In [41]:
# creating an empty list top load the cleaned data
cleaned_text=[]

punct=string.punctuation
stopwords=set(nltk.corpus.stopwords.words('english'))

for word in nltk.word_tokenize(text):
    if word not in punct:
        if word not in stopwords:
            cleaned_text.append(word)
            
print('Original length ==> ',len(text))
print('Length of cleaned text ==>',len(cleaned_text))
print('\n',cleaned_text)

Original length ==>  143
Length of cleaned text ==> 14

 ['india', 'hindi', 'bharat', 'officially', 'republic', 'india', 'country', 'south', 'asia', 'seventh', 'largest', 'country', 'size', 'population']


In [43]:
print(text.upper())

INDIA (HINDI : BHARAT),OFFICIALLY THE REPUBLIC OF INDIA, IS A COUNTRY IN SOUTH ASIA. IT IS THE SEVENTH LARGEST COUNTRY BY SIZE AND POPULATION ;


# STEMMING --- Lemmatization ---- Wordnet

### Stemming

In [45]:
import nltk
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
from nltk.stem import SnowballStemmer

In [48]:
lancaster= LancasterStemmer()
porter=PorterStemmer()
snowball=SnowballStemmer('english')

In [51]:
#stemming just stems the word without looking into grammatical mistake. Let us see one of the example
#lancaster algo is faster than porter but is more complex. Porter stemmer is the oldest algo present and was the most popular to use
#Snowball stemmer, also known as porter 2,is the updated version of porter stemmer and is currently the most popular stemming algorithm
#Snowball stemmer available for multiple language

print('Porter Stemmer')
print(porter.stem("hobby"))
print(porter.stem("hobbies"))
print(porter.stem("computer"))
print(porter.stem("computation"))
print("****************************************************************************************************")

print('lancaster Stemmer')
print(lancaster.stem("hobby"))
print(lancaster.stem("hobbies"))
print(lancaster.stem("computer"))
print(lancaster.stem("computation"))
print("****************************************************************************************************")

print('Snowball Stemmer')
print(snowball.stem("hobby"))
print(snowball.stem("hobbies"))
print(snowball.stem("computer"))
print(snowball.stem("computation"))
print("****************************************************************************************************")

Porter Stemmer
hobbi
hobbi
comput
comput
****************************************************************************************************
lancaster Stemmer
hobby
hobby
comput
comput
****************************************************************************************************
Snowball Stemmer
hobbi
hobbi
comput
comput
****************************************************************************************************


In [52]:
#Another example

print(porter.stem("running"))
print(porter.stem("runs"))
print(porter.stem("ran"))

run
run
ran


### Lemmatization

lemmitization is same as stemming but ensures grammatical mistake. we us word net lemmatizer

In [56]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\jijin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [57]:
lemma=WordNetLemmatizer()

In [58]:
print(lemma.lemmatize("running"))
print(lemma.lemmatize("runs"))
print(lemma.lemmatize("ran"))

running
run
ran


We can see how it takes care of meaning of a word. But it is a time consuming process. Hence use it only when there is a necessity for the meaning and context of words

In [63]:
# We can pass POS tags for the words in a sentence

print(lemma.lemmatize("running",pos='v'))
print(lemma.lemmatize("runs",pos='v'))
print(lemma.lemmatize("ran",pos='v'))

run
run
run


we can see how it changes the part of speech

In [68]:
#Excercise using both stemming and lemma

text="Bring king going anything sing ring nothing thing"

#Stemming
from nltk.stem import PorterStemmer
ps=PorterStemmer()

print("Stemming")
for word in nltk.tokenize.word_tokenize(text):
    print("The stemming for {} is {}".format(word,ps.stem(word)))
print("***************************************************************")   

#Lammetization
from nltk.stem import WordNetLemmatizer
lemma=WordNetLemmatizer()

print("Lemmatizing")
for word in nltk.tokenize.word_tokenize(text):
    print("The lemmatizing of {} is {}".format(word,lemma.lemmatize(word)))

Stemming
The stemming for Bring is bring
The stemming for king is king
The stemming for going is go
The stemming for anything is anyth
The stemming for sing is sing
The stemming for ring is ring
The stemming for nothing is noth
The stemming for thing is thing
***************************************************************
Lemmatizing
The lemmatizing of Bring is Bring
The lemmatizing of king is king
The lemmatizing of going is going
The lemmatizing of anything is anything
The lemmatizing of sing is sing
The lemmatizing of ring is ring
The lemmatizing of nothing is nothing
The lemmatizing of thing is thing


# WordNet

It is used to find the meaning of words synonym and antonym

In [72]:
#Let's find synonyms and antonyms using code

from nltk.corpus import wordnet 

synonym=[]
antonym=[]

#example
for syn in wordnet.synsets("active"):
    for l in syn.lemmas():
        synonym.append(l.name())
        if l.antonyms():
            antonym.append(l.antonyms()[0].name())


print('Synonyms = > ',set(synonym))
print('Antonyms = > ',set(antonym))




Synonyms = >  {'participating', 'active_agent', 'active', 'dynamic', 'alive', 'active_voice', 'fighting', 'combat-ready'}
Antonyms = >  {'stative', 'inactive', 'passive', 'extinct', 'passive_voice', 'quiet', 'dormant'}


In [79]:
syn = wordnet.synsets("active")

In [80]:
syn

[Synset('active_agent.n.01'),
 Synset('active_voice.n.01'),
 Synset('active.n.03'),
 Synset('active.a.01'),
 Synset('active.s.02'),
 Synset('active.a.03'),
 Synset('active.s.04'),
 Synset('active.a.05'),
 Synset('active.a.06'),
 Synset('active.a.07'),
 Synset('active.s.08'),
 Synset('active.a.09'),
 Synset('active.a.10'),
 Synset('active.a.11'),
 Synset('active.a.12'),
 Synset('active.a.13'),
 Synset('active.a.14')]

In [82]:
syn[0].lemmas()

[Lemma('active_agent.n.01.active_agent'), Lemma('active_agent.n.01.active')]

In [85]:
syn[0].lemmas()[0].name()

'active_agent'

In [86]:
syn[0].lemmas()[1].name()

'active'

# Word Embedding , 1_count Vectorization,BOW, n_gram

Count Vectorization : Vectorizes the given words on the basis of frequency of words
    
Types

Bag of words model (BOW)

n_gram

BOW : no grammers required, just keeps the account of words in a particular document

mainly used for feature selection , weights are given to most occuring word. Since stop words will be present, we can't take most occuring word as important . To resolve this issue , "Tf_idf" introduced


n_gram : n_gram is sued in such cases to keep the context of the given text intact. N_gram is the sequence of n words from a given text/document

n1=unigram
n2= bigram

text1= "I went to have a cup of coffee"

unigram  =['I','went','to','have','a','cup','of','coffee']

bigram   =['I went','to have','a cup','of coffee']

trigram  =['I went to','have a cup','of coffee']

Skip gram : skip gram are type of n gram where the words are not necessarily in the same order as are in the given text

In [89]:
#Let us see some examples of Count vectorizer

#### Bag of words (BOW)

In [91]:
# example of single document #without stop words 

from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords

string =[" This is an example of bag of words"]  #Single document
#converting'
vect1=CountVectorizer()
vect1.fit_transform(string)
print("bag of words  :",vect1.get_feature_names())

bag of words  : ['an', 'bag', 'example', 'is', 'of', 'this', 'words']


In [93]:
vect1.vocabulary_  #gives indexes

{'this': 5, 'is': 3, 'an': 0, 'example': 2, 'of': 4, 'bag': 1, 'words': 6}

In [95]:
#Fit and transform and predict if the word is present or not (This is widely used for document (or) subject classification)

c_vect=CountVectorizer()
c_vect.fit(string)  #Training

CountVectorizer()

In [97]:
string2=["Lets understand what is bag of words is"]

c_new_vect=c_vect.transform(string2)   #Testing 
print("Text present at second string similar to string 1 ",c_new_vect.toarray())

Text present at second string similar to string 1  [[0 1 0 2 1 0 1]]


['an'=0, 'bag'=1, 'example'=0, 'is'=2, 'of'=1, 'this'=0, 'words'=1]

In [98]:
#Everything is fine, but you can see we can't determine more important words due to stopwords. 

stpwords=stopwords.words('english')
vect2=CountVectorizer(stop_words=stpwords)

In [99]:
vect2.fit_transform(string2)
print("bag of words : ",vect2.get_feature_names())
print("Index number :",vect2.vocabulary_)

bag of words :  ['bag', 'lets', 'understand', 'words']
Index number : {'lets': 1, 'understand': 2, 'bag': 0, 'words': 3}


Now there are no stopwords seen

In [107]:
#creating userdefined function to use the block of code again and again 
import pandas as pd

In [102]:
def BOW(message,text,cv): #cv=CountVECTORIZER
    cv.fit(message)
    filtext=cv.transform(text)
    return pd.DataFrame(filtext.toarray(),columns=cv.get_feature_names())

In [103]:
cv=CountVectorizer(stop_words=stpwords)  #stpwords=stopwords.words('english')

In [104]:
message=['We are slowly slowly making progress in Natural language Processing','we will get there','But practice is the only mantra']

In [105]:
text=["Natural language Processing is very interesting and will help us practice better making good progress with text"]

In [108]:
BOW(message,text,cv)

get  language  making  mantra  natural  practice  processing  progress  \
0    0         1       1       0        1         1           1         1   

   slowly  
0       0

In [109]:
BOW(message,message,cv)

get  language  making  mantra  natural  practice  processing  progress  \
0    0         1       1       0        1         0           1         1   
1    1         0       0       0        0         0           0         0   
2    0         0       0       1        0         1           0         0   

   slowly  
0       2  
1       0  
2       0

# n-grams

In [111]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import word_tokenize
string=["This is an example of gram "]

vect1=CountVectorizer(ngram_range=(1,1))   #similar to bag of words
v1=vect1.fit_transform(string)

vect2=CountVectorizer(ngram_range=(2,2))
v2=vect2.fit_transform(string)

vect3=CountVectorizer(ngram_range=(2,3))
v3=vect3.fit_transform(string)

vect4=CountVectorizer(ngram_range=(4,4))
v4=vect4.fit_transform(string)

print("1-gram:",vect1.get_feature_names())   #similar to bag of words
print(v1.toarray())
print("***********************************")
print("2 gram:",vect2.get_feature_names())
print(v2.toarray())
print("************************************")
print("3 gram",vect3.get_feature_names())
print(v3.toarray())
print("************************************")
print("4 gram",vect4.get_feature_names())
print(v4.toarray())
print("************************************")

1-gram: ['an', 'example', 'gram', 'is', 'of', 'this']
[[1 1 1 1 1 1]]
***********************************
2 gram: ['an example', 'example of', 'is an', 'of gram', 'this is']
[[1 1 1 1 1]]
************************************
3 gram ['an example', 'an example of', 'example of', 'example of gram', 'is an', 'is an example', 'of gram', 'this is', 'this is an']
[[1 1 1 1 1 1 1 1 1]]
************************************
4 gram ['an example of gram', 'is an example of', 'this is an example']
[[1 1 1]]
************************************


# Word Embedding 2 - Tf-Idf Vectorization

term frequency inverse document frequency

tf idf score = tf *idf

tf term frequency is defined as no of times the words occur in document divided by total no of words in the document

idf is defined as log of total no of document divided by the words appearing in no of document (log has base 2)

In [112]:
#programming

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
tfid=TfidfVectorizer(smooth_idf=False)
doc=["This is an example","We will see how it works","IDF can be confusing"]
doc_vector=tfid.fit_transform(doc)
df=pd.DataFrame(doc_vector.todense(),columns=tfid.get_feature_names())
df

an   be  can  confusing  example       how  idf   is        it       see  \
0  0.5  0.0  0.0        0.0      0.5  0.000000  0.0  0.5  0.000000  0.000000   
1  0.0  0.0  0.0        0.0      0.0  0.408248  0.0  0.0  0.408248  0.408248   
2  0.0  0.5  0.5        0.5      0.0  0.000000  0.5  0.0  0.000000  0.000000   

   this        we      will     works  
0   0.5  0.000000  0.000000  0.000000  
1   0.0  0.408248  0.408248  0.408248  
2   0.0  0.000000  0.000000  0.000000

In [115]:
# using function userdefined

def text_matrix(message,tf):
    term_doc=tf.fit_transform(message)
    return pd.DataFrame(term_doc.toarray(),columns=tf.get_feature_names())

feb_message=["what is covid covid","covid is nothing","covid cases are dropping"]
tf=TfidfVectorizer(smooth_idf=False,stop_words=stpwords) #without dictionary words
text_matrix(feb_message,tf)

cases     covid  dropping  nothing
0  0.000000  1.000000  0.000000  0.00000
1  0.000000  0.430165  0.000000  0.90275
2  0.670092  0.319302  0.670092  0.00000

In [116]:
#Countvectorizer,TF-IDF, n grams program

from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
arr=["Car was cleaned by Jack","Jack was cleaned by car"]
#if you want to take into account as 3 frequencies
cv=CountVectorizer(ngram_range=(2,2))  #n gram specifies your range
x=cv.fit_transform(arr)
#Testing the ngram generation
print("Feature Names \n",cv.get_feature_names())
print("Array \n",x.toarray())

Feature Names 
 ['by car', 'by jack', 'car was', 'cleaned by', 'jack was', 'was cleaned']
Array 
 [[0 1 1 1 0 1]
 [1 0 0 1 1 1]]


In [120]:
#and now testing TFIDF VECTORIZER:
#you can still specify ngrams here   #without stopwords

tf=TfidfVectorizer(ngram_range=(2,2),smooth_idf=False,stop_words=stpwords)
x=tf.fit_transform(arr)
#testing idf value and n gram generation
print("Feature names \n",tf.get_feature_names())
print("Array \n",x.toarray())

Feature names 
 ['car cleaned', 'cleaned car', 'cleaned jack', 'jack cleaned']
Array 
 [[0.70710678 0.         0.70710678 0.        ]
 [0.         0.70710678 0.         0.70710678]]


In [121]:
#Testing TFIDF WITHOUT NORMALISATION
tf=TfidfVectorizer(ngram_range=(2,2),smooth_idf=False,stop_words=stpwords,norm=None)
x=tf.fit_transform(arr)
#testing idf value and n gram generation
print("Feature names \n",tf.get_feature_names())
print("Array \n",x.toarray())

Feature names 
 ['car cleaned', 'cleaned car', 'cleaned jack', 'jack cleaned']
Array 
 [[1.69314718 0.         1.69314718 0.        ]
 [0.         1.69314718 0.         1.69314718]]


# WORD EMBEDDING - 3WORD2Vec

Most advanced word embedding technique than count vectorizer and Tfidf

In [125]:
#!pip install gensim


  Attempting uninstall: Cython
    Found existing installation: Cython 0.29.23
    Uninstalling Cython-0.29.23:
      Successfully uninstalled Cython-0.29.23


In [127]:
#!pip install python-Levenshtein

  Running setup.py clean for python-Levenshtein
Failed to build python-Levenshtein
    Running setup.py install for python-Levenshtein: started
    Running setup.py install for python-Levenshtein: finished with status 'error'


  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\jijin\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jijin\\AppData\\Local\\Temp\\pip-install-080plyxa\\python-levenshtein_e848920cf8364d2b8489ce2d2677dcb8\\setup.py'"'"'; __file__='"'"'C:\\Users\\jijin\\AppData\\Local\\Temp\\pip-install-080plyxa\\python-levenshtein_e848920cf8364d2b8489ce2d2677dcb8\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\jijin\AppData\Local\Temp\pip-wheel-opr43wnz'
       cwd: C:\Users\jijin\AppData\Local\Temp\pip-install-080plyxa\python-levenshtein_e848920cf8364d2b8489ce2d2677dcb8\
  Complete output (27 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\Levenshtein
  copying Levenshtein\StringMat

In [128]:
#Word2Vec

import gensim
import re
import nltk
import string
from gensim.models import Word2Vec
from nltk.corpus import stopwords
import matplotlib.pyplot as plt
%matplotlib inline

In [325]:
paragraph="Coronavirus disease (COVID-19) is an infectious disease caused by a newly discovered coronavirus.Most people infected with the COVID-19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment.  Older people, and those with underlying medical problems like cardiovascular disease, diabetes, chronic respiratory disease, and cancer are more likely to develop serious illness.The best way to prevent and slow down transmission is to be well informed about the COVID-19 virus, the disease it causes and how it spreads. Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face. The COVID-19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes, so it is important that you also practice respiratory etiquette (for example, by coughing into a flexed elbow)."

In [326]:
#Prepocessing the data (for more details on regular expression visit https://regexr.com/)

paragraph=paragraph.translate(str.maketrans('','',string.punctuation))

In [327]:
paragraph

'Coronavirus disease COVID19 is an infectious disease caused by a newly discovered coronavirusMost people infected with the COVID19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment  Older people and those with underlying medical problems like cardiovascular disease diabetes chronic respiratory disease and cancer are more likely to develop serious illnessThe best way to prevent and slow down transmission is to be well informed about the COVID19 virus the disease it causes and how it spreads Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face The COVID19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes so it is important that you also practice respiratory etiquette for example by coughing into a flexed elbow'

In [328]:
text=re.sub(r'\[[0-9]*\]',' ',paragraph)

In [329]:
text

'Coronavirus disease COVID19 is an infectious disease caused by a newly discovered coronavirusMost people infected with the COVID19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment  Older people and those with underlying medical problems like cardiovascular disease diabetes chronic respiratory disease and cancer are more likely to develop serious illnessThe best way to prevent and slow down transmission is to be well informed about the COVID19 virus the disease it causes and how it spreads Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face The COVID19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes so it is important that you also practice respiratory etiquette for example by coughing into a flexed elbow'

In [330]:
text=re.sub(r'\s+',' ',text)

In [331]:
text

'Coronavirus disease COVID19 is an infectious disease caused by a newly discovered coronavirusMost people infected with the COVID19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment Older people and those with underlying medical problems like cardiovascular disease diabetes chronic respiratory disease and cancer are more likely to develop serious illnessThe best way to prevent and slow down transmission is to be well informed about the COVID19 virus the disease it causes and how it spreads Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face The COVID19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes so it is important that you also practice respiratory etiquette for example by coughing into a flexed elbow'

In [332]:
text=re.sub(r'\d+',' ',text) # to remove numbers

In [333]:
text

'Coronavirus disease COVID  is an infectious disease caused by a newly discovered coronavirusMost people infected with the COVID  virus will experience mild to moderate respiratory illness and recover without requiring special treatment Older people and those with underlying medical problems like cardiovascular disease diabetes chronic respiratory disease and cancer are more likely to develop serious illnessThe best way to prevent and slow down transmission is to be well informed about the COVID  virus the disease it causes and how it spreads Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face The COVID  virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes so it is important that you also practice respiratory etiquette for example by coughing into a flexed elbow'

In [334]:
text=text.lower()

In [335]:
text

'coronavirus disease covid  is an infectious disease caused by a newly discovered coronavirusmost people infected with the covid  virus will experience mild to moderate respiratory illness and recover without requiring special treatment older people and those with underlying medical problems like cardiovascular disease diabetes chronic respiratory disease and cancer are more likely to develop serious illnessthe best way to prevent and slow down transmission is to be well informed about the covid  virus the disease it causes and how it spreads protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face the covid  virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes so it is important that you also practice respiratory etiquette for example by coughing into a flexed elbow'

In [336]:
text=re.sub(r'\s+',' ',text)

In [337]:
text

'coronavirus disease covid is an infectious disease caused by a newly discovered coronavirusmost people infected with the covid virus will experience mild to moderate respiratory illness and recover without requiring special treatment older people and those with underlying medical problems like cardiovascular disease diabetes chronic respiratory disease and cancer are more likely to develop serious illnessthe best way to prevent and slow down transmission is to be well informed about the covid virus the disease it causes and how it spreads protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face the covid virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes so it is important that you also practice respiratory etiquette for example by coughing into a flexed elbow'

In [338]:
#Preparing the dataset

sentences=nltk.sent_tokenize(text)
sentences

['coronavirus disease covid is an infectious disease caused by a newly discovered coronavirusmost people infected with the covid virus will experience mild to moderate respiratory illness and recover without requiring special treatment older people and those with underlying medical problems like cardiovascular disease diabetes chronic respiratory disease and cancer are more likely to develop serious illnessthe best way to prevent and slow down transmission is to be well informed about the covid virus the disease it causes and how it spreads protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face the covid virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes so it is important that you also practice respiratory etiquette for example by coughing into a flexed elbow']

In [339]:
sent_word=[nltk.word_tokenize(sentence) for sentence in sentences]
print(sent_word)

[['coronavirus', 'disease', 'covid', 'is', 'an', 'infectious', 'disease', 'caused', 'by', 'a', 'newly', 'discovered', 'coronavirusmost', 'people', 'infected', 'with', 'the', 'covid', 'virus', 'will', 'experience', 'mild', 'to', 'moderate', 'respiratory', 'illness', 'and', 'recover', 'without', 'requiring', 'special', 'treatment', 'older', 'people', 'and', 'those', 'with', 'underlying', 'medical', 'problems', 'like', 'cardiovascular', 'disease', 'diabetes', 'chronic', 'respiratory', 'disease', 'and', 'cancer', 'are', 'more', 'likely', 'to', 'develop', 'serious', 'illnessthe', 'best', 'way', 'to', 'prevent', 'and', 'slow', 'down', 'transmission', 'is', 'to', 'be', 'well', 'informed', 'about', 'the', 'covid', 'virus', 'the', 'disease', 'it', 'causes', 'and', 'how', 'it', 'spreads', 'protect', 'yourself', 'and', 'others', 'from', 'infection', 'by', 'washing', 'your', 'hands', 'or', 'using', 'an', 'alcohol', 'based', 'rub', 'frequently', 'and', 'not', 'touching', 'your', 'face', 'the', 'cov

In [340]:
punc=string.punctuation
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [341]:
for i in range(len(sent_word)):
    sent_word[i]=[word for word in sent_word[i] if word not in stopwords.words('english') if word not in punc]

In [342]:
sent_word

[['coronavirus',
  'disease',
  'covid',
  'infectious',
  'disease',
  'caused',
  'newly',
  'discovered',
  'coronavirusmost',
  'people',
  'infected',
  'covid',
  'virus',
  'experience',
  'mild',
  'moderate',
  'respiratory',
  'illness',
  'recover',
  'without',
  'requiring',
  'special',
  'treatment',
  'older',
  'people',
  'underlying',
  'medical',
  'problems',
  'like',
  'cardiovascular',
  'disease',
  'diabetes',
  'chronic',
  'respiratory',
  'disease',
  'cancer',
  'likely',
  'develop',
  'serious',
  'illnessthe',
  'best',
  'way',
  'prevent',
  'slow',
  'transmission',
  'well',
  'informed',
  'covid',
  'virus',
  'disease',
  'causes',
  'spreads',
  'protect',
  'others',
  'infection',
  'washing',
  'hands',
  'using',
  'alcohol',
  'based',
  'rub',
  'frequently',
  'touching',
  'face',
  'covid',
  'virus',
  'spreads',
  'primarily',
  'droplets',
  'saliva',
  'discharge',
  'nose',
  'infected',
  'person',
  'coughs',
  'sneezes',
  'impo

In [343]:
#Training The Word2Vec Model
model=Word2Vec(sent_word,min_count=1)
words=model.wv.key_to_index
words1=model.wv.get_vecattr

In [344]:
words

{'disease': 0,
 'covid': 1,
 'respiratory': 2,
 'virus': 3,
 'infected': 4,
 'spreads': 5,
 'people': 6,
 'underlying': 7,
 'medical': 8,
 'problems': 9,
 'like': 10,
 'cardiovascular': 11,
 'elbow': 12,
 'diabetes': 13,
 'treatment': 14,
 'chronic': 15,
 'cancer': 16,
 'likely': 17,
 'develop': 18,
 'serious': 19,
 'older': 20,
 'without': 21,
 'special': 22,
 'requiring': 23,
 'best': 24,
 'recover': 25,
 'illness': 26,
 'moderate': 27,
 'mild': 28,
 'experience': 29,
 'coronavirusmost': 30,
 'discovered': 31,
 'newly': 32,
 'caused': 33,
 'infectious': 34,
 'illnessthe': 35,
 'way': 36,
 'flexed': 37,
 'coughs': 38,
 'primarily': 39,
 'droplets': 40,
 'saliva': 41,
 'discharge': 42,
 'nose': 43,
 'person': 44,
 'sneezes': 45,
 'prevent': 46,
 'important': 47,
 'also': 48,
 'practice': 49,
 'etiquette': 50,
 'example': 51,
 'coughing': 52,
 'face': 53,
 'touching': 54,
 'frequently': 55,
 'rub': 56,
 'based': 57,
 'alcohol': 58,
 'using': 59,
 'hands': 60,
 'washing': 61,
 'infection

In [345]:
words1

<bound method KeyedVectors.get_vecattr of <gensim.models.keyedvectors.KeyedVectors object at 0x0000023C0D57D880>>

In [346]:
#Test the word Vector

vector=model.wv['covid']
print(vector)

[-8.6176936e-03  3.6709218e-03  5.1901368e-03  5.7368414e-03
  7.4733677e-03 -6.1913831e-03  1.1114787e-03  6.0831690e-03
 -2.8408985e-03 -6.1907722e-03 -4.1391022e-04 -8.3867675e-03
 -5.5924854e-03  7.1185417e-03  3.3695656e-03  7.2230510e-03
  6.8130400e-03  7.5293891e-03 -3.7978704e-03 -5.6777470e-04
  2.3573311e-03 -4.5189606e-03  8.3933892e-03 -9.8801423e-03
  6.7462446e-03  2.9046885e-03 -4.9544140e-03  4.3921475e-03
 -1.7397100e-03  6.7100707e-03  9.9702403e-03 -4.3752035e-03
 -5.8418897e-04 -5.7172272e-03  3.8447902e-03  2.8063066e-03
  6.8961494e-03  6.1015161e-03  9.5198704e-03  9.2700776e-03
  7.8990636e-03 -6.9817486e-03 -9.1460636e-03 -3.6333376e-04
 -3.0902263e-03  7.8927092e-03  5.9178984e-03 -1.5510609e-03
  1.5132880e-03  1.7901127e-03  7.8273965e-03 -9.5252460e-03
 -2.0781127e-04  3.4574789e-03 -9.3968492e-04  8.3830301e-03
  9.0228515e-03  6.5341969e-03 -7.0696609e-04  7.7171177e-03
 -8.5387509e-03  3.1963552e-03 -4.6369815e-03 -5.0778617e-03
  3.5864965e-03  5.38771

In [347]:
#this is how it vectorize

In [348]:
#most similar words
similar=model.wv.most_similar('infectious',topn=5)
similar

[('nose', 0.2063399851322174),
 ('sneezes', 0.17618191242218018),
 ('others', 0.15973719954490662),
 ('touching', 0.1527964174747467),
 ('develop', 0.14591798186302185)]

In [352]:
#some words similarity
model.wv.similarity(w1='infection',w2='develop')

0.09081279

In [353]:
#filter on non similarity
model.wv.doesnt_match(["covid","spread","china"])

'covid'

In [354]:
#covid doesn't match with spread and china. spread and china are more similar

# Corse sine similarity (not needed to know just understand how we use)

from sklearn.manifold import TSNE
vocab=['nose','sneezes','others','touching','develop','covid']
def tsne_plot(model):
    label=[]
    wordvecs=[]
    
    for word in vocab:
        wordvecs.append(model[word])
        labels.append(word)
        
    tsne_model=TSNE(perplexity=3,n_components=2,init='pca',random_state=42)
    coordinates=tsne_model.fit_transform(wordvecs)
    
    x=[]
    y=[]
    for value in coordinates:
        x.append(value[0])
        y.append(value[1])
        
    plt.figure(figsize=(10,6))
    
    for i in range(len(x)):
        plt.scatter(x[i],y[i])
        plt.annotate(labels[i],xy=(x[i],y[i]),xytext=(2,2),textcoords='offset points',ha='right')
        plt.show()
        
tsne_plot(model)
plt.show()